logging:
  level:
    root: DEBUG
    pl.adkr.hsbc.challenge: DEBUG
    org.springframework: INFO
    org.hibernate: ERROR
    org.apache: INFO
    sun.rmi: INFO
    io.springfox: INFO
    springfox: INFO
    com.zaxxer : INFO


message:
  validation:
    len:
      min: 3
      max: 140